email:
    smtpHost: ENC[AES256_GCM,data:V80iPvZ18OQBOrGtTa4=,iv:e5zbmr3LiZMHy0aZj+Gr1rMGIkB00ZjYol+Sl21Zkr8=,tag:TsnlRSD6Kj6be511PfUGFw==,type:str]
    smtpPort: ENC[AES256_GCM,data:UC/4,iv:c5Y4xRR2w/BxeCrz1PzYD6TnwWnvX/nDkpGWoZw0sp8=,tag:EG7rpKz9xG+yIuRq2/PkSQ==,type:int]
    smtpFrom: ENC[AES256_GCM,data:BGElBtAS54H4ub0kyfz6,iv:BW8WVoEWmFaCiGHPcBvWqcrtYf5wSgUUyMrNnRlk2Ug=,tag:Qqt3Iic8t80s0tqXtLdOUA==,type:str]
    smtpUsername: ENC[AES256_GCM,data:oepP8XQ+LA==,iv:Pd68MrEfPSE8wS68yaEMwoWao3B0PoOs6JUm+iZzKPc=,tag:4TpxAHye7as8+dJO99TyIA==,type:str]
    smtpPasswd: ENC[AES256_GCM,data:EiV93BhiS88QLfpUZDLNv+61Ew==,iv:tR3hSg0TtZswzhS624rc/8x4Zf1OZfoTp7oglz5/CvE=,tag:MJvNYdV02UoqjHa9Bm/NfA==,type:str]
cloudflare:
    email: null
    dnsApiToken: null
    zoneApiToken: null
s3:
    accessKeyId: ENC[AES256_GCM,data:Tia0rSQqVJH+u7IuCZInrXwoIK8=,iv:B5Uch4ch4axiB1mq1jhDLN13npoqQReX03/gf0jV8nI=,tag:AuAL+qdtcXQSIWYOkBL6ew==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:uIbjvpYieGXsZPvHvnWspyFc5S14TKQZy05e+MaEeWh9CCnrw/SLKg==,iv:CmxmSpQR2grKpsNFv8mJj29omjd1CJk70rSHAc2pDlg=,tag:bYEjo31q8DFtSv9rq8SZ+g==,type:str]
    bucket: ENC[AES256_GCM,data:6aMbqvNFz0CPbu9mxreDsOo07XvxHjNWPvcCEdPAAPBkSES1HIx6abAg,iv:V3R1UTnqW1PRENqT+jAV8GVDTY4/CNMV4LJM20/A0yU=,tag:BU0PdbQuGVi6+fsi44NS7Q==,type:str]
    region: ENC[AES256_GCM,data:wBXAG1Ne9DgOd1y1ENU=,iv:Sfnrac76TpqDhnZVKy67rIOrBWBsVD7BGDeo2KsWPW4=,tag:g8tcrYUkWniW9vqlfIzg0A==,type:str]
traefik:
    basicAuthPasswd: ENC[AES256_GCM,data:FF/NRj4=,iv:iiq2/Wi20ATk0p8+6/XgfBUcKhNNdpzgUTBxcHfoqno=,tag:5o1ue4LeI0IcxpmSb167DA==,type:str]
grafana:
    passwd: ENC[AES256_GCM,data:Sv1SUWM=,iv:4aMcI9V6FrolaxPRksPCS96uCg3r5edgwCfTl2G2jQ8=,tag:zkU1PIb7cPt7k6PQbUdccQ==,type:str]
velero:
    repositoryPassword: ENC[AES256_GCM,data:qrGT/W3GEJLcHkY7bRHESGDqegYERqnay+2cMXhkW5R5lrq8yplOgKnc+sQ=,iv:P8WrobwA07sihWBROYpIhDdxjnnauTe21dAdGuEw48o=,tag:kiIz38F6ii+INViD9bxmhA==,type:str]
sops:
    age:
        - recipient: age1h0sp353y3qnkv40dtremtl7e6uxp5dx35m4r4tr78fe8fle0m9eqhd2g78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUk05VjRGSTlvQUdZSFli
            TXJPQTFnSm5DS1R4djc4ZjhHcDNqejEwNmhZCnlQeVcwTXdabUZYU1YrMVFoUlU0
            UmFscEVoR28zNXUzRXdQUDUrZlJrWWsKLS0tIE1aUkNJR2RXR3JEV3FwM1RNVSs1
            eG9tOTlmWG9tTU44alBDVE95R3BNSkkKZP/tkUzxkLa522KkiSYnOTQ59g+HhaZD
            L4Lw6JzI3DWAxIrKh4Phwn+MinZZ+UAtkY5EUEHCCK+OBiC5xgFnxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T06:06:05Z"
    mac: ENC[AES256_GCM,data:jMfr+HUn8t/57VnSfUZkR/Z3ncKhgX/UgbIUUui62owjKgZaUNJHR9xVcDBMKUVJD/PHbm0c4mARZBn6QlFSKzUOvxrhRyIFAKOgzRmc7Fpv+/756qgP7lJvBRRh8fC/+6TFNPkV9CEDQiLHLfrwLaYIxL9O7HbyMiR/nfxqXYA=,iv:piWxZZfq5DzDyqjcS5NV/AXFRkhc3T2e9C6JGYzERcU=,tag:Zu3PCIYT4pRggviXDcvB7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
